import { Booking } from "../types";

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "book-001",
    bookingRef: "DRV-2024-8821",
    instructorId: "inst-001",
    studentId: "stu-current",
    lessonType: "standard",
    transmission: "manual",
    date: "2024-12-28",
    startTime: "10:00",
    durationHours: 1,
    priceInPence: 6500,
    status: "confirmed",
    meetingPoint: "Outside Tesco Express, 42 Victoria Street, London SW1H 0ET",
    createdAt: "2024-12-20",
  },
  {
    id: "book-002",
    bookingRef: "DRV-2024-7134",
    instructorId: "inst-001",
    studentId: "stu-current",
    lessonType: "standard",
    transmission: "manual",
    date: "2024-12-14",
    startTime: "14:00",
    durationHours: 1,
    priceInPence: 6500,
    status: "completed",
    meetingPoint: "Outside Tesco Express, 42 Victoria Street, London SW1H 0ET",
    createdAt: "2024-12-07",
  },
  {
    id: "book-003",
    bookingRef: "DRV-2024-6895",
    instructorId: "inst-001",
    studentId: "stu-current",
    lessonType: "standard",
    transmission: "manual",
    date: "2024-12-07",
    startTime: "09:00",
    durationHours: 2,
    priceInPence: 13000,
    status: "completed",
    meetingPoint: "Outside Tesco Express, 42 Victoria Street, London SW1H 0ET",
    createdAt: "2024-11-30",
  },
];
