import { Instructor, WeeklyAvailability } from "../types";

const defaultAvailability: WeeklyAvailability = {
  monday: [
    { startTime: "09:00", endTime: "10:00", available: true },
    { startTime: "10:00", endTime: "11:00", available: true },
    { startTime: "11:00", endTime: "12:00", available: false },
    { startTime: "14:00", endTime: "15:00", available: true },
    { startTime: "15:00", endTime: "16:00", available: true },
    { startTime: "16:00", endTime: "17:00", available: true },
  ],
  tuesday: [
    { startTime: "09:00", endTime: "10:00", available: true },
    { startTime: "10:00", endTime: "11:00", available: false },
    { startTime: "14:00", endTime: "15:00", available: true },
    { startTime: "15:00", endTime: "16:00", available: true },
    { startTime: "17:00", endTime: "18:00", available: true },
  ],
  wednesday: [
    { startTime: "09:00", endTime: "10:00", available: true },
    { startTime: "10:00", endTime: "11:00", available: true },
    { startTime: "11:00", endTime: "12:00", available: true },
    { startTime: "14:00", endTime: "15:00", available: false },
    { startTime: "15:00", endTime: "16:00", available: true },
  ],
  thursday: [
    { startTime: "09:00", endTime: "10:00", available: false },
    { startTime: "10:00", endTime: "11:00", available: true },
    { startTime: "14:00", endTime: "15:00", available: true },
    { startTime: "15:00", endTime: "16:00", available: true },
    { startTime: "16:00", endTime: "17:00", available: true },
  ],
  friday: [
    { startTime: "09:00", endTime: "10:00", available: true },
    { startTime: "10:00", endTime: "11:00", available: true },
    { startTime: "11:00", endTime: "12:00", available: false },
    { startTime: "14:00", endTime: "15:00", available: true },
  ],
  saturday: [
    { startTime: "09:00", endTime: "10:00", available: true },
    { startTime: "10:00", endTime: "11:00", available: true },
    { startTime: "11:00", endTime: "12:00", available: true },
  ],
  sunday: [],
};

export const MOCK_INSTRUCTORS: Instructor[] = [
  {
    id: "inst-001",
    slug: "sarah-thompson-london",
    name: "Sarah Thompson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=b6e3f4",
    location: {
      city: "London",
      postcode: "SW1A 1AA",
      coverageRadius: 5,
      coordinates: [51.501, -0.1257],
    },
    adiNumber: "123456",
    dvsaApproved: true,
    transmission: "both",
    pricePerHour: 6500,
    rating: 4.9,
    reviewCount: 127,
    lessonsGiven: 1843,
    passRate: 96,
    experience: 8,
    featured: true,
    badges: ["top-rated", "dvsa-approved", "high-pass-rate"],
    vehicle: { make: "Vauxhall", model: "Corsa", year: 2023, color: "White" },
    languages: ["English", "Spanish"],
    specialisms: ["Nervous pupils", "Pass Plus", "Motorway lessons"],
    bio: "With over 8 years of experience as a DVSA-approved ADI, I specialise in helping nervous learners build confidence behind the wheel. My calm, patient approach has helped over 1,800 students pass their practical test, many on their first attempt. I cover all areas of Central and South London.",
    packages: [
      { id: "pkg-1a", name: "Single Lesson", hours: 1, priceInPence: 6500 },
      { id: "pkg-1b", name: "Block of 5", hours: 5, priceInPence: 30000, saving: 2500, popular: true },
      { id: "pkg-1c", name: "Block of 10", hours: 10, priceInPence: 57500, saving: 7500 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-002",
    slug: "james-wilson-manchester",
    name: "James Wilson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=james&backgroundColor=c0aede",
    location: {
      city: "Manchester",
      postcode: "M1 1AB",
      coverageRadius: 8,
      coordinates: [53.4808, -2.2426],
    },
    adiNumber: "234567",
    dvsaApproved: true,
    transmission: "manual",
    pricePerHour: 5500,
    rating: 4.8,
    reviewCount: 89,
    lessonsGiven: 1205,
    passRate: 94,
    experience: 6,
    featured: true,
    badges: ["top-rated", "dvsa-approved", "quick-responder"],
    vehicle: { make: "Ford", model: "Fiesta", year: 2022, color: "Blue" },
    languages: ["English"],
    specialisms: ["Young drivers", "Intensive courses", "Test preparation"],
    bio: "A passionate driving instructor based in Manchester City Centre. I offer structured lesson plans tailored to each student's learning pace. Specialising in intensive courses for those who want to qualify quickly without compromising on safety.",
    packages: [
      { id: "pkg-2a", name: "Single Lesson", hours: 1, priceInPence: 5500 },
      { id: "pkg-2b", name: "Block of 5", hours: 5, priceInPence: 25000, saving: 2500, popular: true },
      { id: "pkg-2c", name: "Block of 10", hours: 10, priceInPence: 48000, saving: 7000 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-003",
    slug: "priya-patel-birmingham",
    name: "Priya Patel",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=ffd5dc",
    location: {
      city: "Birmingham",
      postcode: "B1 1BB",
      coverageRadius: 6,
      coordinates: [52.4862, -1.8904],
    },
    adiNumber: "345678",
    dvsaApproved: true,
    transmission: "both",
    pricePerHour: 5000,
    rating: 4.9,
    reviewCount: 203,
    lessonsGiven: 2100,
    passRate: 97,
    experience: 11,
    featured: true,
    badges: ["top-rated", "dvsa-approved", "high-pass-rate"],
    vehicle: { make: "Toyota", model: "Yaris", year: 2023, color: "Silver" },
    languages: ["English", "Gujarati", "Hindi"],
    specialisms: ["Nervous pupils", "Female students preferred", "Pass Plus"],
    bio: "Award-winning driving instructor with 11 years of experience in Birmingham. I hold a Grade A ADI qualification and have helped over 2,000 learners pass their test. I offer lessons in English, Gujarati, and Hindi, making me the ideal choice for learners from diverse backgrounds.",
    packages: [
      { id: "pkg-3a", name: "Single Lesson", hours: 1, priceInPence: 5000 },
      { id: "pkg-3b", name: "Block of 5", hours: 5, priceInPence: 22500, saving: 2500, popular: true },
      { id: "pkg-3c", name: "Block of 10", hours: 10, priceInPence: 43000, saving: 7000 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-004",
    slug: "david-mcallister-edinburgh",
    name: "David McAllister",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=david&backgroundColor=d1d4f9",
    location: {
      city: "Edinburgh",
      postcode: "EH1 1AB",
      coverageRadius: 10,
      coordinates: [55.9533, -3.1883],
    },
    adiNumber: "456789",
    dvsaApproved: true,
    transmission: "automatic",
    pricePerHour: 5500,
    rating: 4.7,
    reviewCount: 64,
    lessonsGiven: 780,
    passRate: 89,
    experience: 4,
    featured: false,
    badges: ["dvsa-approved", "quick-responder"],
    vehicle: { make: "Volkswagen", model: "Polo", year: 2022, color: "Grey" },
    languages: ["English", "Scottish Gaelic"],
    specialisms: ["Automatic cars", "Rural driving", "Elderly learners"],
    bio: "Edinburgh-based automatic driving specialist covering the city centre and surrounding areas. I provide a friendly, pressure-free environment ideal for older learners or those who find manual coordination challenging.",
    packages: [
      { id: "pkg-4a", name: "Single Lesson", hours: 1, priceInPence: 5500 },
      { id: "pkg-4b", name: "Block of 5", hours: 5, priceInPence: 25000, saving: 2500, popular: true },
      { id: "pkg-4c", name: "Block of 10", hours: 10, priceInPence: 48000, saving: 7000 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-005",
    slug: "emma-davies-cardiff",
    name: "Emma Davies",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma&backgroundColor=b6e3f4",
    location: {
      city: "Cardiff",
      postcode: "CF10 1AB",
      coverageRadius: 7,
      coordinates: [51.4816, -3.1791],
    },
    adiNumber: "567890",
    dvsaApproved: true,
    transmission: "manual",
    pricePerHour: 4800,
    rating: 4.8,
    reviewCount: 91,
    lessonsGiven: 1150,
    passRate: 93,
    experience: 7,
    featured: false,
    badges: ["dvsa-approved", "high-pass-rate"],
    vehicle: { make: "Nissan", model: "Micra", year: 2021, color: "Red" },
    languages: ["English", "Welsh"],
    specialisms: ["Young drivers", "Theory test support", "Motorway lessons"],
    bio: "Bilingual English and Welsh driving instructor covering all of Cardiff and the Vale of Glamorgan. I take a structured approach to learning, providing detailed feedback after every lesson to ensure continuous progress.",
    packages: [
      { id: "pkg-5a", name: "Single Lesson", hours: 1, priceInPence: 4800 },
      { id: "pkg-5b", name: "Block of 5", hours: 5, priceInPence: 22000, saving: 2000, popular: true },
      { id: "pkg-5c", name: "Block of 10", hours: 10, priceInPence: 42000, saving: 6000 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-006",
    slug: "ryan-o-brien-leeds",
    name: "Ryan O'Brien",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ryan&backgroundColor=c0aede",
    location: {
      city: "Leeds",
      postcode: "LS1 1AA",
      coverageRadius: 9,
      coordinates: [53.8008, -1.5491],
    },
    adiNumber: "678901",
    dvsaApproved: true,
    transmission: "both",
    pricePerHour: 5200,
    rating: 4.6,
    reviewCount: 55,
    lessonsGiven: 630,
    passRate: 88,
    experience: 3,
    featured: false,
    badges: ["dvsa-approved", "new-instructor", "quick-responder"],
    vehicle: { make: "Hyundai", model: "i10", year: 2023, color: "Orange" },
    languages: ["English"],
    specialisms: ["Student drivers", "Budget packages", "Evening lessons"],
    bio: "Newer to the industry but not to driving — I bring fresh, modern teaching techniques combined with genuine enthusiasm for helping people learn. Evening and weekend slots available, perfect for those with busy schedules.",
    packages: [
      { id: "pkg-6a", name: "Single Lesson", hours: 1, priceInPence: 5200 },
      { id: "pkg-6b", name: "Block of 5", hours: 5, priceInPence: 24000, saving: 2000, popular: true },
      { id: "pkg-6c", name: "Block of 10", hours: 10, priceInPence: 46000, saving: 6000 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-007",
    slug: "amara-osei-bristol",
    name: "Amara Osei",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=amara&backgroundColor=ffd5dc",
    location: {
      city: "Bristol",
      postcode: "BS1 1AB",
      coverageRadius: 6,
      coordinates: [51.4545, -2.5879],
    },
    adiNumber: "789012",
    dvsaApproved: true,
    transmission: "both",
    pricePerHour: 5300,
    rating: 4.9,
    reviewCount: 112,
    lessonsGiven: 1420,
    passRate: 95,
    experience: 9,
    featured: true,
    badges: ["top-rated", "dvsa-approved", "high-pass-rate"],
    vehicle: { make: "Kia", model: "Picanto", year: 2022, color: "White" },
    languages: ["English", "Twi"],
    specialisms: ["Nervous pupils", "Pass Plus", "Dual carriageway driving"],
    bio: "Bristol's most-reviewed driving instructor. My holistic approach focuses on building safe driving habits, not just passing the test. I've helped over 1,400 students achieve their licence, and I offer free theory test advice with every block booking.",
    packages: [
      { id: "pkg-7a", name: "Single Lesson", hours: 1, priceInPence: 5300 },
      { id: "pkg-7b", name: "Block of 5", hours: 5, priceInPence: 24000, saving: 2500, popular: true },
      { id: "pkg-7c", name: "Block of 10", hours: 10, priceInPence: 46000, saving: 7000 },
    ],
    availability: defaultAvailability,
  },
  {
    id: "inst-008",
    slug: "karen-armstrong-newcastle",
    name: "Karen Armstrong",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=karen&backgroundColor=d1d4f9",
    location: {
      city: "Newcastle",
      postcode: "NE1 1AB",
      coverageRadius: 8,
      coordinates: [54.9784, -1.6174],
    },
    adiNumber: "890123",
    dvsaApproved: true,
    transmission: "manual",
    pricePerHour: 4500,
    rating: 4.7,
    reviewCount: 78,
    lessonsGiven: 940,
    passRate: 91,
    experience: 5,
    featured: false,
    badges: ["dvsa-approved", "high-pass-rate"],
    vehicle: { make: "Ford", model: "Ka", year: 2021, color: "Purple" },
    languages: ["English"],
    specialisms: ["Young drivers", "Rural and urban mixed routes", "Test prep"],
    bio: "Newcastle-based instructor covering the city, Gateshead, and surrounding areas. I use a mix of theory discussion and practical skills to give learners a well-rounded understanding of the Highway Code before they sit their test.",
    packages: [
      { id: "pkg-8a", name: "Single Lesson", hours: 1, priceInPence: 4500 },
      { id: "pkg-8b", name: "Block of 5", hours: 5, priceInPence: 20500, saving: 2000, popular: true },
      { id: "pkg-8c", name: "Block of 10", hours: 10, priceInPence: 39000, saving: 6000 },
    ],
    availability: defaultAvailability,
  },
];
