import { Review } from "../types";

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-001",
    instructorId: "inst-001",
    studentId: "stu-001",
    studentName: "Tom Harrison",
    rating: 5,
    comment: "Sarah is an absolute legend! I was so nervous before my first lesson but she made me feel completely at ease. Passed first time after just 32 hours. Couldn't recommend her more.",
    lessonType: "standard",
    createdAt: "2024-11-15",
    passed: true,
  },
  {
    id: "rev-002",
    instructorId: "inst-001",
    studentId: "stu-002",
    studentName: "Fatima Al-Hassan",
    rating: 5,
    comment: "I tried two other instructors before Sarah and gave up both times. With Sarah I passed in 6 weeks. Her patience and clear explanations made all the difference. Absolutely brilliant.",
    lessonType: "standard",
    createdAt: "2024-10-22",
    passed: true,
  },
  {
    id: "rev-003",
    instructorId: "inst-001",
    studentId: "stu-003",
    studentName: "Charlie Browning",
    rating: 4,
    comment: "Really good instructor. Very calm and methodical. My only note would be that I would have liked a bit more motorway practice before my test, but overall I passed so can't complain!",
    lessonType: "test-prep",
    createdAt: "2024-09-10",
    passed: true,
  },
  {
    id: "rev-004",
    instructorId: "inst-001",
    studentId: "stu-004",
    studentName: "Neha Sharma",
    rating: 5,
    comment: "Sarah teaches in both English and Spanish which was perfect for my mum who wanted to follow my progress. She explains everything so clearly. First time pass after 28 hours.",
    lessonType: "standard",
    createdAt: "2024-08-05",
    passed: true,
  },
  {
    id: "rev-005",
    instructorId: "inst-002",
    studentId: "stu-005",
    studentName: "Jamie Forsyth",
    rating: 5,
    comment: "James ran an intensive course for me over two weeks. Absolute professional. His structured approach meant I knew exactly what to work on every lesson. Passed with only 2 minors!",
    lessonType: "test-prep",
    createdAt: "2024-11-01",
    passed: true,
  },
  {
    id: "rev-006",
    instructorId: "inst-002",
    studentId: "stu-006",
    studentName: "Sophie Clarke",
    rating: 5,
    comment: "Super friendly and always on time. James gave me loads of confidence when I was struggling with roundabouts. Would 100% recommend to anyone in Manchester.",
    lessonType: "standard",
    createdAt: "2024-10-14",
    passed: true,
  },
  {
    id: "rev-007",
    instructorId: "inst-003",
    studentId: "stu-007",
    studentName: "Ravi Kumar",
    rating: 5,
    comment: "Priya taught me in Gujarati and English, which was perfect. She's incredibly knowledgeable and patient. I felt fully prepared on the day of my test. Highly recommend!",
    lessonType: "standard",
    createdAt: "2024-11-20",
    passed: true,
  },
  {
    id: "rev-008",
    instructorId: "inst-003",
    studentId: "stu-008",
    studentName: "Alice Pemberton",
    rating: 5,
    comment: "Priya has a gift for teaching. She identifies your weak areas quickly and focuses on them without making you feel bad. Her 97% pass rate is well deserved. Brilliant instructor.",
    lessonType: "standard",
    createdAt: "2024-10-05",
    passed: true,
  },
  {
    id: "rev-009",
    instructorId: "inst-007",
    studentId: "stu-009",
    studentName: "Marcus Reid",
    rating: 5,
    comment: "Amara is truly exceptional. Calm, encouraging, and extremely knowledgeable. He spotted bad habits I didn't even know I had and helped me correct them. Passed with 3 minors.",
    lessonType: "standard",
    createdAt: "2024-11-10",
    passed: true,
  },
  {
    id: "rev-010",
    instructorId: "inst-007",
    studentId: "stu-010",
    studentName: "Lucy Fairweather",
    rating: 5,
    comment: "Best driving instructor in Bristol, full stop. I'd recommend Amara to absolutely anyone. He's professional, punctual, kind, and genuinely wants you to succeed.",
    lessonType: "pass-plus",
    createdAt: "2024-09-28",
    passed: true,
  },
];
