import { Testimonial } from "../types";

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "test-001",
    name: "Tom Harrison",
    city: "London",
    avatar: "TH",
    quote: "I passed first time after just 32 hours with Sarah. The booking system made it so easy to find the right instructor. Absolute game changer.",
    passed: true,
    rating: 5,
    instructorName: "Sarah Thompson",
  },
  {
    id: "test-002",
    name: "Jamie Forsyth",
    city: "Manchester",
    avatar: "JF",
    quote: "Found James through MCO-DS and did an intensive course in two weeks. Passed with only 2 minors. The platform made everything seamless from start to finish.",
    passed: true,
    rating: 5,
    instructorName: "James Wilson",
  },
  {
    id: "test-003",
    name: "Ravi Kumar",
    city: "Birmingham",
    avatar: "RK",
    quote: "Being able to filter by language spoken was a huge bonus. Found Priya who teaches in Gujarati and English — exactly what I needed. Passed first attempt!",
    passed: true,
    rating: 5,
    instructorName: "Priya Patel",
  },
  {
    id: "test-004",
    name: "Lucy Fairweather",
    city: "Bristol",
    avatar: "LF",
    quote: "The reviews on this platform are so accurate. Amara was exactly as described — patient, professional, and brilliant at his job. Worth every penny.",
    passed: true,
    rating: 5,
    instructorName: "Amara Osei",
  },
  {
    id: "test-005",
    name: "Sophie Clarke",
    city: "Manchester",
    avatar: "SC",
    quote: "I was really anxious about learning to drive in my late 20s. MCO-DS helped me find an instructor who specialised in nervous pupils. I passed!",
    passed: true,
    rating: 5,
    instructorName: "James Wilson",
  },
  {
    id: "test-006",
    name: "Marcus Reid",
    city: "Bristol",
    avatar: "MR",
    quote: "The online booking and calendar system is so much better than trying to text back and forth. Everything is clear, confirmed instantly, and easy to manage.",
    passed: true,
    rating: 5,
    instructorName: "Amara Osei",
  },
];
